#if !canImport(ObjectiveC)
import XCTest

extension CommonMarkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__CommonMarkTests = [
        ("testMarkdownToArrayOfBlocks", testMarkdownToArrayOfBlocks),
        ("testMarkdownToHTML", testMarkdownToHTML),
        ("testMarkdownToNode", testMarkdownToNode),
        ("testReadMarkdownFromNonInvalidFilenameReturnsNil", testReadMarkdownFromNonInvalidFilenameReturnsNil),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(CommonMarkTests.__allTests__CommonMarkTests),
    ]
}
#endif
